#!/usr/bin/env bash

# Update package index
apt-get update

# Install nginx server
apt-get -y install nginx

# Allow traffic on port 80 (HTTP) in the firewall
sudo ufw allow 'Nginx HTTP'

# Create a default index.html file with "Hello World!"
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'

# Restart nginx service to apply changes
sudo service nginx restart
