#!/bin/bash

# Use awk to parse Apache log file, group visitors by IP and HTTP status code, and display data
awk '{print $1, $9}' apache-access.log | sort | uniq -c | awk '{print $1, $2, $3}' | sort -nr
