#!/usr/bin/env bash
# This script displays different messages based on the iteration number

# Initialize counter
counter=0

# Loop until counter is equal to 10
while [ $counter -lt 10 ]
do
    # Increment counter
    ((counter++))
    
    # Check the current iteration number
    if [ $counter -eq 4 ]; then
        echo "bad luck"
    elif [ $counter -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
done
